### PR TITLE
fixes issue 56

### PR DESCRIPTION
**Pull request by KristianKuhlmann**
(https://github.com/SeriousM/WPFLocalizationExtension/issues/56)

 - prevents lock on Dispatcher when accessing CurrentCulture from Background-Thread

### CODE REVIEW

**Comment by SeriousM** [comment]
thanks!

**Comment by KristianKuhlmann** [comment]
How should I provide the demo to reproduce these issues?

**Comment by MrCircuit** [comment]
Using https://gist.github.com or other online storage services.

**Comment by KristianKuhlmann** [comment]
Ok, here you go: https://drive.google.com/open?id=0B5ILrljVcMRhUlNnYmN6WVFPdjQ
The zip contains a simple solution with a commandline app showing up both issues. I hope you may be able to build some unit tests from this.

**Pull request merged**
